name: infinite-db
channels:
  - defaults
  - conda-forge
  - microsoft
dependencies:
  - python>=3.12
  - pip
  - gensim
  - numpy
  - nodejs==16.13.0
  - pip:
      - requests
      - matplotlib
      - fuzzywuzzy
      - numpy
      - cython
      - POT
      - gensim
      - wordfreq
